# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

# This is a reusable workflow called by other workflows to run
# different groups of tests categorized by their types.
#
# Tests collected in ../../../tests/test_groups.yml, are grouped
# based on
# their
# * type
#   + pr_gate
#   + nightly
#   + experimental
# * compute
#   + cpu
#   + gpu
#   + spark
#
# In order to speed up testing, the testing workflows will run the
# tests in parallel according to the groups obtained from this
# action.

name: Tests

on:
  workflow_call:
    inputs:
      compute:
        required: false
        type: string
        default: cpu
        description: Test compute - cpu, gpu or spark.  It is only
          used for nightly not pr_gate
      dockerfile:
        required: false
        type: string
        default: tools/docker/Dockerfile
        description: Path to the Dockerfile used for building the
          test environment
      test_groups_yml:
        required: false
        type: string
        default: tests/test_groups.yml
        description: Path to test group configuration file relative
          to the repo root
      timeout-minutes:
        required: true
        type: number
      tools_dir:
        required: false
        type: string
        default: .github/workflows/tools
        description: Path to the workflow tools
      type:
        required: true
        type: string
        description: Type of test - pr_gate or nightly
    secrets:
      CLOUD_SERVICE_SECRET:
        required: true
        description: secret or private key for accessing the cloud
          service
env:
  PR_REF: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || github.ref }}

jobs:
  get-test-groups:
    runs-on: ubuntu-24.04
    outputs:
      groups: ${{ steps.get-test-groups.outputs.groups }}
    steps:
      - name: Check out repository code from the PR
        uses: actions/checkout@v7
        with:
          ref: ${{ env.PR_REF }}
          allow-unsafe-pr-checkout: true

      - name: Get test group names
        id: get-test-groups
        shell: bash
        run: |
          bash '${{ inputs.tools_dir }}/get_test_groups.sh' \
               '${{ inputs.test_groups_yml }}' \
               '${{ inputs.type }}' \
               '${{ inputs.compute }}'

  execute-tests:
    name: ${{ join(matrix.*, ', ') }}
    needs: get-test-groups
    # Docker and sshpass are required on the runner.
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 6
      matrix:
        python-version:
          - '3.10'
          - '3.11'
        group: ${{ fromJSON(needs.get-test-groups.outputs.groups) }}
    env:
      CLOUD_SERVICE: ${{ vars.CLOUD_SERVICE }}
      CLOUD_SERVICE_ENVS: ${{ vars.CLOUD_SERVICE_ENVS }}
      # * GPU tests should run on GPUs.
      # * cpu-nightly needs to run on larger CPU runner with 32GB memory.
      # * Otherwise, standard runner is enough.
      EXTRA_VM_REQUIRED: ${{ contains(matrix.group, 'gpu') || (contains(inputs.type, 'nightly') && contains(matrix.group, 'cpu')) }}
    steps:
      - name: Check out repository code from the PR
        uses: actions/checkout@v7
        with:
          ref: ${{ env.PR_REF }}
          allow-unsafe-pr-checkout: true
      
      - name: Generate unique VM name and Docker image tag
        run: |
          if [[ '${{ github.event_name }}' == 'pull_request_target' ]]
          then
              commit="$(echo ${{ github.event.pull_request.head.sha }} | head -c 5)"
              vm_name_template="vm_${{ github.event.number }}_${commit}_XXXXXX"
          else
              commit="$(echo ${{ github.sha }} | head -c 5)"
              vm_name_template="vm_${commit}_XXXXXX"
          fi
          image_tag="reco-${commit}-${{ github.run_attempt }}"
          vm_name="$(mktemp -u ${vm_name_template})"

          # Export VM_NAME and IMAGE_TAG for subsequent steps
          echo "IMAGE_TAG=${image_tag}" >> "${GITHUB_ENV}"
          echo "VM_NAME=${vm_name}" >> "${GITHUB_ENV}"

      - name: Setup VM
        if: ${{ fromJSON(env.EXTRA_VM_REQUIRED) }}
        env:
          CLOUD_SERVICE_SECRET: ${{ secrets.CLOUD_SERVICE_SECRET }}
        # The script for creating a VM must explictly set the
        # environment variable SSH_DEST into $GITHUB_ENV.
        run: |
          create_script_name='create.sh'
          create_script="${{ inputs.tools_dir }}/${CLOUD_SERVICE@L}/${create_script_name}"
          if [[ ! -f ${create_script} ]]; then
              create_script="${{ inputs.tools_dir }}/${create_script_name}"
          fi
          bash "${create_script}" \
               "${VM_NAME}" \
               '${{ inputs.type }}' \
               '${{ matrix.group }}'
          bash '${{ inputs.tools_dir }}/post_create.sh'

      - name: Build image
        run: |
          bash '${{ inputs.tools_dir }}/build_image.sh' \
               "${IMAGE_TAG}" \
               '${{ inputs.dockerfile }}' \
               '${{ matrix.group }}' \
               '${{ matrix.python-version }}'

      - name: Execute tests in container
        run: |
          bash '${{ inputs.tools_dir }}/run_tests.sh' \
               "${IMAGE_TAG}" \
               '${{ inputs.test_groups_yml }}' \
               '${{ inputs.type }}' \
               '${{ matrix.group }}'

      - name: Clean up
        if: ${{ always() && fromJSON(env.EXTRA_VM_REQUIRED) }}
        env:
          CLOUD_SERVICE_SECRET: ${{ secrets.CLOUD_SERVICE_SECRET }}
        run: |
          delete_script_name='delete.sh'
          delete_script="${{ inputs.tools_dir }}/${CLOUD_SERVICE@L}/${delete_script_name}"
          if [[ ! -f ${delete_script} ]]; then
              delete_script="${{ inputs.tools_dir }}/${delete_script_name}"
          fi
          bash "${delete_script}" "${VM_NAME}"
