# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-tests
description: "Submit experiment to AzureML cluster"
inputs:
  EXP_NAME:
    required: true
    description: AzureML experiment Name
  ENV_NAME:
    required: true
    description: AzureML environment Name
  TEST_KIND:
    required: true
    description: Type of test - unit or nightly
  AZUREML_TEST_UMI_CLIENT_ID:
    required: true
    description: AzureML User-managed identity client ID
  AZUREML_TEST_UMI_TENANT_ID:
    required: true
    description: AzureML User-managed identity tenant ID
  AZUREML_TEST_UMI_SUB_ID:
    required: true
    description: AzureML User-managed identity subscription ID
  AZUREML_TEST_SUBID:
    required: true
    description: AzureML subscription ID
  PYTHON_VERSION:
    required: true
    description: Python version used for the tests
  TEST_GROUP:
    required: true
    description: Test group defined in test_group.py
  RG:
    required: false
    description: AzureML resource group name
    default: "recommenders_project_resources"
  WS:
    required: false
    description: AzureML workspace name
    default: "azureml-test-workspace"
  LOG_DIR:
    required: false
    description: Directory storing the test logs
    default: "test_logs"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install AzureML Python SDK
      shell: bash
      run: pip install --quiet "azure-ai-ml>1,<2" mlflow "azureml-mlflow>1,<2" 
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.AZUREML_TEST_UMI_CLIENT_ID }}
        tenant-id: ${{ inputs.AZUREML_TEST_UMI_TENANT_ID }}
        subscription-id: ${{ inputs.AZUREML_TEST_UMI_SUB_ID }}
    - name: Submit tests to AzureML
      shell: bash
      run: |
        echo "::group::Running tests ..."
        python tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py \
          --subid ${{ inputs.AZUREML_TEST_SUBID }} \
          --rg ${{ inputs.RG }} \
          --ws ${{ inputs.WS }} \
          --cluster ${{ contains(inputs.TEST_GROUP, 'gpu') && 'gpu-cluster' || 'cpu-cluster' }} \
          --expname ${{ inputs.EXP_NAME }} \
          --envname ${{ inputs.ENV_NAME }} \
          --testkind ${{ inputs.TEST_KIND}} \
          --python-version ${{ inputs.PYTHON_VERSION }} \
          --testgroup ${{ inputs.TEST_GROUP }} \
          --sha ${GITHUB_SHA}
        echo "::endgroup::"
    - name: Post tests
      if: ${{ ! cancelled() }}
      shell: bash
      run: |
        echo "::group::Pytest logs"
        python tests/ci/azureml_tests/post_pytest.py \
          --subid ${{ inputs.AZUREML_TEST_SUBID }} \
          --rg ${{ inputs.RG }} \
          --ws ${{ inputs.WS }} \
          --expname ${{ inputs.EXP_NAME }} \
          --log-dir ${{ inputs.LOG_DIR }}
        echo "::endgroup::"
    - name: Save logs
      if: ${{ ! cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.TEST_GROUP }}-python${{ inputs.PYTHON_VERSION }}
        path: ${{ inputs.LOG_DIR }}
