# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-tests
description: "Submit experiment to AzureML cluster"
inputs:
  # azureml experiment name
  EXP_NAME:
    required: true
    type: string
  # type of test - unit or nightly
  TEST_KIND:
    required: true
    type: string
  # test environment - cpu, gpu or spark
  TEST_ENV:
    required: false
    type: string
  # azureml compute credentials
  AZUREML_TEST_CREDENTIALS:
    required: true
    type: string
  # azureml compute subid
  AZUREML_TEST_SUBID:
    required: true
    type: string
  # python version
  PYTHON_VERSION:
    required: true
    type: string
  # test group name
  TEST_GROUP:
    required: true
    type: string
  # cpu cluster name
  CPU_CLUSTER_NAME:
    required: false
    type: string
    default: "cpu-cluster"
  # gpu cluster name
  GPU_CLUSTER_NAME:
    required: false
    type: string
    default: "gpu-cluster"
  # AzureML resource group name
  RG:
    required: false
    type: string
    default: "recommenders_project_resources"  
  # AzureML workspace name
  WS:
    required: false
    type: string
    default: "azureml-test-workspace"  
  # test logs path
  TEST_LOGS_PATH:
    required: false
    type: string
    default: '"test_logs.log"'
  # pytest exit code
  PYTEST_EXIT_CODE:
    required: false
    type: string
    default: "pytest_exit_code.log"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with: 
        python-version: "3.8"
    - name: Install azureml-core and azure-cli on a GitHub hosted server
      shell: bash
      run: pip install --quiet azureml-core azure-cli
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{inputs.AZUREML_TEST_CREDENTIALS}}
    - name: Install wheel package
      shell: bash
      run: pip install --quiet wheel
    - name: Create wheel from setup.py
      shell: bash
      run: python setup.py --quiet bdist_wheel
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Submit CPU tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'cpu')
      run: >-
          python tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py --clustername ${{inputs.CPU_CLUSTER_NAME}}
          --subid ${{inputs.AZUREML_TEST_SUBID}} --reponame "recommenders" --branch ${{ steps.extract_branch.outputs.branch }}
          --rg ${{inputs.RG}} --wsname ${{inputs.WS}} --expname ${{inputs.EXP_NAME}}_${{inputs.TEST_GROUP}}
          --testlogs ${{inputs.TEST_LOGS_PATH}} --testkind ${{inputs.TEST_KIND}} 
          --conda_pkg_python ${{inputs.PYTHON_VERSION}} --testgroup ${{inputs.TEST_GROUP}}
          --pytestargs "--durations 0 --disable-warnings" 
    - name: Submit GPU tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'gpu')
      run: >-
          echo "Skipping GPU" >> ${{inputs.TEST_LOGS_PATH}}
    - name: Submit PySpark tests to AzureML
      shell: bash
      if: contains(inputs.TEST_GROUP, 'spark')
      run: >-
          echo "Skipping PySpark" >> ${{inputs.TEST_LOGS_PATH}}
    - name: Print test logs
      shell: bash
      run: cat ${{inputs.TEST_LOGS_PATH}}
    - name: Get exit status
      shell: bash
      id: exit_status
      run: echo ::set-output name=code::$(cat ${{inputs.PYTEST_EXIT_CODE}})
    - name: Check Success/Failure
      if: ${{ steps.execute_tests.outputs.code != 0 }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('All tests did not pass!')
