//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendersDemo.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecommendersDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] dislike {
            get {
                object obj = ResourceManager.GetObject("dislike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] after_like {
            get {
                object obj = ResourceManager.GetObject("after_like", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] before_dislike {
            get {
                object obj = ResourceManager.GetObject("before_dislike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] before_like {
            get {
                object obj = ResourceManager.GetObject("before_like", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string LocalPopularEndpoint {
            get {
                return ResourceManager.GetString("LocalPopularEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/microsoft/recommenders.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }

        internal static string LocalRecommendationEndpoint {
            get {
                return ResourceManager.GetString("LocalRecommendationEndpoint", resourceCulture);
            }
        }
        
        internal static string PopularEndpoint {
            get {
                return ResourceManager.GetString("PopularEndpoint", resourceCulture);
            }
        }
        
        internal static string RecommendationEndpoint {
            get {
                return ResourceManager.GetString("RecommendationEndpoint", resourceCulture);
            }
        }
        
        internal static string SearchEndpoint {
            get {
                return ResourceManager.GetString("SearchEndpoint", resourceCulture);
            }
        }
        
        internal static string LocalSearchEndpoint {
            get {
                return ResourceManager.GetString("LocalSearchEndpoint", resourceCulture);
            }
        }
        
        internal static string PersonasEndpoint {
            get {
                return ResourceManager.GetString("PersonasEndpoint", resourceCulture);
            }
        }
        
        internal static string AlgorithmDescriptionEndpoint {
            get {
                return ResourceManager.GetString("AlgorithmDescriptionEndpoint", resourceCulture);
            }
        }
        
        internal static string OnboardingEndpoint {
            get {
                return ResourceManager.GetString("OnboardingEndpoint", resourceCulture);
            }
        }
        
        internal static string LocalPersonasEndpoint {
            get {
                return ResourceManager.GetString("LocalPersonasEndpoint", resourceCulture);
            }
        }
        
        internal static string SarDescription {
            get {
                return ResourceManager.GetString("SarDescription", resourceCulture);
            }
        }
        
        internal static string LgbmDescription {
            get {
                return ResourceManager.GetString("LgbmDescription", resourceCulture);
            }
        }
        
        internal static string InternalErrorMessage {
            get {
                return ResourceManager.GetString("InternalErrorMessage", resourceCulture);
            }
        }
        
        internal static string LikeMoviesBeforeRecsWarningMessage {
            get {
                return ResourceManager.GetString("LikeMoviesBeforeRecsWarningMessage", resourceCulture);
            }
        }
        
        internal static string NotMovieObjectErrorMessage {
            get {
                return ResourceManager.GetString("NotMovieObjectErrorMessage", resourceCulture);
            }
        }
        
        internal static string NoInternetMessage {
            get {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }
    }
}
