# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.

######################################################################
# Configuration for scripts to setup VMs on CompShare
######################################################################
apt_mirror: mirrors.ucloud.cn
scripts:
    # The script for VM creation must set the environment variable
    # SSH_DEST into $GITHUB_ENV for subsequent steps.
    create: create.sh
    delete: delete.sh
