# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

# This is a reusable workflow called by other workflows to run
# different groups of tests categorized by their types.
#
# Tests collected in tests/test_groups.yml, are grouped based on their
# * type
#   + pr_gate
#   + nightly
#   + experimental
# * compute
#   + cpu
#   + gpu
#   + spark
#
# In order to speed up testing, the testing workflows will run the
# tests in parallel according to the groups obtained from this action.

name: Tests

on:
  workflow_call:
    inputs:
      compute:
        required: false
        type: string
        default: cpu
        description: Test compute - cpu, gpu or spark.  It is only used for
          nightly not pr_gate
      config-file:
        required: false
        type: string
        default: tests/test_groups.yml
        description: Path to test group configuration file relative
          to the repo root
      dockerfile:
        required: false
        type: string
        default: tools/docker/Dockerfile
        description: Path to the Dockerfile used for building the
          test environment
      timeout-minutes:
        required: true
        type: number
      type:
        required: true
        type: string
        description: Type of test - pr_gate or nightly

jobs:
  get-test-groups:
    # yq is required to run .github/actions/get-test-groups, and it
    # is preinstalled on ubuntu-24.04
    # (https://github.com/actions/runner-images/blob/9b8c9709431a8d2b295fd46cf96f283d671f20d9/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L100)
    runs-on: ubuntu-24.04
    outputs:
      groups: ${{ steps.get-test-groups.outputs.groups }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Get test group names
        id: get-test-groups
        shell: bash
        run: |
          if [[ ${{ inputs.type }} == "nightly" ]]; then
            TEST_GROUPS_STR=$(yq -o json -I 0 \
              '[.${{ inputs.type }} | keys | .[] | select(contains("${{ inputs.compute }}"))]' \
              ${{ inputs.config-file }})
          else
            TEST_GROUPS_STR=$(yq -o json -I 0 \
              '.${{ inputs.type }} | keys' ${{ inputs.config-file }})
          fi
          echo "Test Groups: ${TEST_GROUPS_STR}"
          echo "groups=${TEST_GROUPS_STR}" >> $GITHUB_OUTPUT

  execute-tests:
    name: ${{ join(matrix.*, ', ') }}
    needs: get-test-groups
    # Docker is required on the runner.
    # GPU tests should run on GPUs,
    # cpu-nightly needs to run on larger CPU runner,
    # otherwise, standard runner is enough.
    runs-on: |-
      ${{ case(
        contains(matrix.group, 'gpu'), 'GPU',
        contains(inputs.type, 'nightly') && contains(matrix.group, 'cpu'), 'CPU',
        'ubuntu-24.04'
      ) }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
        group: ${{ fromJSON(needs.get-test-groups.outputs.groups) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Build image
        env:
          IMAGE_TAG: reco-${{ github.sha }}-${{ github.run_attempt }}-${{ matrix.group }}-${{ matrix.python-version }}
        run: |
          docker build . \
            -t ${IMAGE_TAG} \
            -f ${{ inputs.dockerfile }} \
            --build-arg COMPUTE=${{ contains(matrix.group, 'gpu') && 'gpu' || 'cpu' }} \
            --build-arg EXTRAS=[dev${{ contains(matrix.group, 'gpu') && ',gpu' || '' }}${{ contains(matrix.group, 'spark') && ',spark' || '' }}] \
            --build-arg GIT_REF= \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }}

      - name: Execute tests in container
        env:
          IMAGE_TAG: reco-${{ github.sha }}-${{ github.run_attempt }}-${{ matrix.group }}-${{ matrix.python-version }}
          RECO_VENV_DIR: /root/.venvs/Recommenders
        run: |
          # Check hardware specs
          echo "CPU: $(nproc)"
          echo "Memory:"
          free -h

          # Run tests
          if [[ ${{ matrix.group }} =~ 'gpu' ]]; then
            nvidia-smi && \
            docker run --rm --gpus all ${IMAGE_TAG} \
              bash -lc 'source /root/.sdkman/bin/sdkman-init.sh && source ${{ env.RECO_VENV_DIR }}/bin/activate && \
                        pytest --durations 0 \
                          $(yq ".${{ inputs.type }}.${{ matrix.group }} | map(@sh) | join(\" \")" "${{ inputs.config-file }}")'
          else
            docker run --rm ${IMAGE_TAG} \
              bash -lc 'source /root/.sdkman/bin/sdkman-init.sh && source ${{ env.RECO_VENV_DIR }}/bin/activate && \
                        pytest --durations 0 \
                          $(yq ".${{ inputs.type }}.${{ matrix.group }} | map(@sh) | join(\" \")" "${{ inputs.config-file }}")'
          fi

      - name: Clean up
        if: always()
        env:
          IMAGE_TAG: reco-${{ github.sha }}-${{ github.run_attempt }}-${{ matrix.group }}-${{ matrix.python-version }}
        run: |
          if docker image ls | grep ${IMAGE_TAG} > /dev/null; then
            if docker container ls -a | grep ${IMAGE_TAG} > /dev/null; then
              docker container rm -f $(docker ps -a | grep "${IMAGE_TAG}" | awk '{print $1}')
            fi
            docker image rm ${IMAGE_TAG}
          fi
