# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

# This is a reusable workflow called by other workflows to run
# different groups of tests categorized by their types.

name: Tests

on:
  workflow_call:
    inputs:
      compute:
        required: false
        type: string
        default: cpu
        description: Test compute - cpu, gpu or spark
      config-file:
        required: false
        type: string
        default: tests/test_groups.yml
        description: Path to test group configuration file relative
          to the repo root
      dockerfile:
        required: false
        type: string
        default: tools/docker/Dockerfile
        description: Path to the Dockerfile used for building the
          test environment
      timeout-minutes:
        required: true
        type: number
      type:
        required: true
        type: string
        description: Type of test - pr_gate or nightly

jobs:
  get-test-groups:
    # yq is required to run .github/actions/get-test-groups, and it
    # is preinstalled on ubuntu-24.04
    # (https://github.com/actions/runner-images/blob/9b8c9709431a8d2b295fd46cf96f283d671f20d9/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L100)
    runs-on: ubuntu-24.04
    outputs:
      groups: ${{ steps.get-test-groups.outputs.groups }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Get test group names
        id: get-test-groups
        uses: ./.github/actions/get-test-groups
        with:
          compute: ${{ inputs.compute }}
          config-file: ${{ inputs.config-file }}
          type: ${{ inputs.type }}

  execute-tests:
    name: ${{ join(matrix.*, ', ') }}
    needs: get-test-groups
    runs-on: ${{ contains(matrix.group, 'gpu') && 'self-hosted' || 'ubuntu-24.04' }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash -li {0}
    strategy:
      matrix:
        python-version:
          # - '3.8'
          # - '3.9'
          - '3.10'
          # - '3.11'
        group: ${{ fromJSON(needs.get-test-groups.outputs.groups) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install dependencies and execute tests
        run: |
          # Install Recommenders and its dependencies
          if [[ "${{ matrix.group }}" =~ spark ]]; then
            sdk use java 21.0.2-open
          fi

          uv venv --python ${{ matrix.python-version }}
          source .venv/bin/activate
        
          if [[ ! "${{ matrix.group }}" =~ gpu ]]; then
            uv pip install pytest-xdist
          fi

          EXTRAS=dev${{ contains(matrix.group, 'gpu') && ',gpu' || '' }}${{ contains(matrix.group, 'spark') && ',spark' || '' }}
          uv pip install "recommenders[${EXTRAS}] @ ."

          # Execute tests
          pytest --durations 0 $(yq ".${{ inputs.type }}.${{ matrix.group }} | map(@sh) | join(\" \")" "${{ inputs.config-file }}")
